### ISSUE TITLE
App does not update on android

### ISSUE THREAD

**Issue by tvouga** [indie-pocket/indie-pocket#13]

**Comment by tvouga** [comment]
Still on 5.1 on android. Version 5.2 from applivery does not install upon manual download; version 5.3 not available yet (staging? where is it available?)

**Comment by ineiti** [comment]
Uploaded 0.5.3 (I insist on the `0.` ;)

With regard to staging, can you give some more information? Did you install staging? Do you want to install it? Does the version say `0.5.1-s`?

**Comment by ineiti** [comment]
If the problem is resolved, please give a short description how you resolved it, and close the comment.

**Comment by ineiti** [comment]
time out - closing. Please re-open if it's still a problem.
